include("distributions/core.jl")
include("distributions/registration.jl")
include("distributions/continuous.jl")
include("distributions/discrete.jl")
include("distributions/structured.jl")
include("distributions/gaussian_process.jl")
include("distributions/truncated.jl")
